---
categories:
- ""
- ""
date: "2017-10-31T21:28:43-05:00"
description: ""
draft: false
image: finance.jpg
keywords: ""
slug: peppapig
title: Youth Risk Behavior Surveillance and Discrimination Analysis
---



<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<p>Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns. You will work with a selected group of variables from a random sample of observations during one of the years the YRBSS was conducted.</p>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical. The meaning of each variable can be found by bringing up the help file:</p>
<p>?yrbss</p>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1…
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema…
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, …
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;…
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa…
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1…
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2, …
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not …
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not…
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, …
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,…
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, …
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;…</code></pre>
<p>Before you carry on with your analysis, it’s is always a good idea to check with <code>skimr::skim()</code> to get a feel for missing values, summary statistics of numerical variables, and a very rough histogram.</p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>You will first start with analyzing the <code>weight</code> of participants in kilograms. Using visualization and summary statistics, describe the distribution of weights. How many observations are we missing weights from?</p>
<pre class="r"><code>glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1…
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema…
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, …
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;…
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa…
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1…
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2, …
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not …
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not…
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, …
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,…
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, …
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;…</code></pre>
<pre class="r"><code>skim(yrbss) # 1004 weight entries missing</code></pre>
<table>
<caption>(#tab:eda_on_weight)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
<pre class="r"><code>weight_analysis &lt;- yrbss %&gt;% 
  
  #select the weight variable
  select(weight) %&gt;%
  
  #remove NAs
  na.omit() %&gt;% 
  
#plot the histogram
ggplot(aes(x=weight))+
  geom_histogram(bins=30)+
  theme_bw()+
  labs(title=&quot;Distribution of weights&quot;)

#print our histogram
weight_analysis</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/eda_on_weight-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Next, consider the possible relationship between a high schooler’s weight and their physical activity. Plotting the data is a useful first step because it helps us quickly visualize trends, identify strong associations, and develop research questions.</p>
<p>Let’s create a new variable in the dataframe <code>yrbss</code>, called <code>physical_3plus</code> , which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise. You may also want to calculate the number and % of those who are and are not active for more than 3 days. RUse the <code>count()</code> function and see if you get the same results as <code>group_by()... summarise()</code></p>
<pre class="r"><code># Scatterplotting relationship between a high schooler’s weight and their physical activity

yrbss_new&lt;- yrbss %&gt;% 
  
  #omit the NAs
  na.omit(weight,physically_active_7d) %&gt;% 
  
  #group by physically active
  group_by(physically_active_7d)%&gt;%
  
  #create a column for the mean weight
  mutate(mean_weight = mean(weight)) 

ggplot(yrbss_new,aes(y=weight, x=physically_active_7d))+
  
  #create a box plot
  geom_boxplot(aes(group=as.character(physically_active_7d))) + 
  theme_bw()+
  
  #add proper labels
  labs(title=&quot;Plotting relationship between a high\nschooler’s weight and their physical activity&quot;,
       x=&quot;physical active days&quot;,
       y=&quot;weight&quot;)+
  theme(plot.title=element_text(size=15,face=&quot;bold&quot;,hjust=0.5))</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/mutate_and_count-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#plot relationship between a high schooler’s weight and their physical activity by geom_col
yrbss_new%&gt;% 
  group_by(physically_active_7d) </code></pre>
<pre><code>## # A tibble: 8,351 × 14
## # Groups:   physically_active_7d [8]
##      age gender grade hispanic race    height weight helmet_12m text_while_driv…
##    &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           
##  1    15 female 9     hispanic Native…   1.73   84.4 never      30              
##  2    15 female 9     not      Black …   1.6    55.8 never      0               
##  3    15 female 9     not      Black …   1.5    46.7 did not r… did not drive   
##  4    15 female 9     not      Black …   1.57   67.1 did not r… did not drive   
##  5    15 female 9     not      Black …   1.68   69.8 did not r… 0               
##  6    15 female 9     not      Black …   1.65   66.7 did not r… did not drive   
##  7    16 male   9     not      Black …   1.68   74.8 never      0               
##  8    16 male   9     not      Black …   1.85   74.4 did not r… did not drive   
##  9    15 male   9     not      Black …   1.78   70.3 did not r… 0               
## 10    14 male   9     not      Black …   1.73   73.5 never      did not drive   
## # … with 8,341 more rows, and 5 more variables: physically_active_7d &lt;int&gt;,
## #   hours_tv_per_school_day &lt;chr&gt;, strength_training_7d &lt;int&gt;,
## #   school_night_hours_sleep &lt;chr&gt;, mean_weight &lt;dbl&gt;</code></pre>
<pre class="r"><code>#create a new box plot with the mean weight
ggplot(yrbss_new,aes(y=mean_weight, x=physically_active_7d)) + 
  geom_bar(stat=&quot;summary&quot;, fun.y=&quot;mean&quot;)+
  theme_bw()+
  labs(title=&quot;Plotting relationship between a high\nschooler’s weight and their physical activity&quot;,
       x=&quot;physical active days&quot;,
       y=&quot;mean_weight&quot;)+
  theme(plot.title=element_text(size=15,face=&quot;bold&quot;,hjust=0.5))</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/mutate_and_count-2.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#create a new dataframe that contains a new column to determine the persons that are physically active
yrbss_new&lt;-yrbss_new %&gt;%
  na.omit(weight,physically_active_7d) %&gt;% 
  mutate(physical_3plus=ifelse(physically_active_7d&gt;=3, &quot;yes&quot;, &quot;no&quot;), weight_count=count(weight)) %&gt;% 
  group_by(physical_3plus) 
  ggplot(yrbss_new,aes(y=weight_count, x=physical_3plus))+
  geom_col()+
  theme_bw()+
  labs(title=&quot;Weight count versus physical activity&quot;)+
  theme(plot.title=element_text(size=15,face=&quot;bold&quot;,hjust=0.5))</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/mutate_and_count-3.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#create a new dataframe to count the persons that are physically active and the proportion of physically active persons
weight_exercise &lt;- yrbss_new %&gt;% 
  na.omit(weight,physically_active_7d) %&gt;% 
  select(physical_3plus,weight) %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarize(num_physical=count(physical_3plus)) %&gt;%
  mutate(sum=sum(num_physical),per_physical=num_physical/sum)%&gt;%
  select(physical_3plus,num_physical,per_physical)
weight_exercise</code></pre>
<pre><code>## # A tibble: 2 × 3
##   physical_3plus num_physical per_physical
##   &lt;chr&gt;                 &lt;int&gt;        &lt;dbl&gt;
## 1 no                     2656        0.318
## 2 yes                    5695        0.682</code></pre>
<p>Can you provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</p>
<pre class="r"><code>total_pop&lt;-2656+5695
prop.test(2656,total_pop,0.95)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  2656 out of total_pop
## X-squared = 70199, df = 1, p-value &lt;2e-16
## alternative hypothesis: true p is not equal to 0.95
## 95 percent confidence interval:
##  0.308 0.328
## sample estimates:
##     p 
## 0.318</code></pre>
<p>–&gt; OUR ANSWER BELOW &lt;—</p>
<p>As shown in Chunk 6, sample proportion is 0.318 and n is 8351 giving us a SE of 0.0051 and t-score (z-score) of 1.96.
Thus the Confidence Interval for the population proportion of high schools that are NOT active 3 or more days per week is (0.308,0.328).</p>
<p>–&gt; END OF OUR ANSWER &lt;—</p>
<p>Make a boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Is there a relationship between these two variables? What did you expect and why?</p>
<pre class="r"><code>#create a boxplot of &quot;physical_3plus&quot; vs &quot;weight&quot;
yrbss_boxplot &lt;-yrbss_new
ggplot(yrbss_new,aes(x=weight, y=physical_3plus))+
  geom_boxplot()+
  theme_bw()+
  labs(title=&quot;Variable physical_3plus\nvs variable weight&quot;)+
  theme(plot.title=element_text(size=15,face=&quot;bold&quot;,hjust=0.5))</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#create variable to determine the physically active persons and omit the NAs
weight_exercise_plot &lt;- yrbss %&gt;% 
  mutate(physical_3plus=ifelse(physically_active_7d&gt;=3, &quot;yes&quot;, &quot;no&quot;)) %&gt;% 
  na.omit(weight,physically_active_7d)</code></pre>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean, SD, etc. weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code>#create a new dataframe and group by physical_3plus
ci_weight_exercise_count&lt;-yrbss_new %&gt;%
  
  group_by(physical_3plus) %&gt;%
  
  #create the statistics we want to analyse
  summarize(mean=mean(weight),
            median=median(weight,na.rm=TRUE),
            sd=sd(weight),
                  count=n(),
                  se=sd/sqrt(count),
            max=max(weight),
            min=min(weight),
            t_critical=qt(0.975,count-1),
            margin_of_error=t_critical*se,
            lower_ci_95=mean-t_critical*se,
            higher_ci_95=mean+t_critical*se)

#print the statistics
ci_weight_exercise_count</code></pre>
<pre><code>## # A tibble: 2 × 12
##   physical_3plus  mean median    sd count    se   max   min t_critical
##   &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
## 1 no              67.1   62.6  18.0  2656 0.349  181.  31.8       1.96
## 2 yes             68.7   65.8  16.4  5695 0.218  160.  35.4       1.96
## # … with 3 more variables: margin_of_error &lt;dbl&gt;, lower_ci_95 &lt;dbl&gt;,
## #   higher_ci_95 &lt;dbl&gt;</code></pre>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Write the null and alternative hypotheses for testing whether mean weights are different for those who exercise at least times a week and those who don’t.</p>
<pre class="r"><code>#create variable to determine the physically active persons
yrbss&lt;- yrbss %&gt;%
  mutate(physical_3plus=ifelse(physically_active_7d&gt;=3, &quot;yes&quot;, &quot;no&quot;))

#run the t-test between weight and physical_3plus
t.test(weight ~ physical_3plus, data = yrbss)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group no mean in group yes 
##              66.7              68.4</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we will introduce a new function, <code>hypothesize</code>, that falls into the infer workflow. You will use this method for conducting hypothesis tests.</p>
<p>But first, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>#create a dataframe to compute the difference of means
obs_diff &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))
obs_diff</code></pre>
<pre><code>## Response: weight (numeric)
## Explanatory: physical_3plus (factor)
## # A tibble: 1 × 1
##    stat
##   &lt;dbl&gt;
## 1  1.77</code></pre>
<p>Notice how you can use the functions specify and calculate again like you did for calculating confidence intervals. Here, though, the statistic you are searching for is the difference in means, with the order being yes - no != 0.</p>
<p>After you have initialized the test, you need to simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>null_dist &lt;- yrbss %&gt;%
  
  # specify variables
  specify(weight ~ physical_3plus) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))

null_dist</code></pre>
<pre><code>## Response: weight (numeric)
## Explanatory: physical_3plus (factor)
## Null Hypothesis: independence
## # A tibble: 1,000 × 2
##    replicate    stat
##        &lt;int&gt;   &lt;dbl&gt;
##  1         1 -0.0731
##  2         2 -0.155 
##  3         3 -0.301 
##  4         4  0.230 
##  5         5 -0.167 
##  6         6 -0.603 
##  7         7 -0.0324
##  8         8 -0.107 
##  9         9 -0.0553
## 10        10  0.326 
## # … with 990 more rows</code></pre>
<p>Here, <code>hypothesize</code> is used to set the null hypothesis as a test for independence, i.e., that there is no difference between the two population means. In one sample cases, the null argument can be set to <em>point</em> to test a hypothesis relative to a point estimate.</p>
<p>Also, note that the <code>type</code> argument within generate is set to permute, which is the argument when generating a null distribution for a hypothesis test.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram(bins=30)+
  theme_bw()+
  labs(title=&quot;Null distribution&quot;)+
  theme(plot.title=element_text(size=15,face=&quot;bold&quot;,hjust=0.5))</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/visualize%20distribution-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least “obs_stat” of “r obs_diff %&gt;% pull() %&gt;% round(2)”?</p>
<p>We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>#compute the p_value for the observed statistics
null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/p-value%20computing-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>This the standard workflow for performing hypothesis tests.</p>
</div>
</div>
<div id="imdb-ratings-differences-between-directors" class="section level1">
<h1>IMDB ratings: Differences between directors</h1>
<p>Recall the IMBD ratings data. I would like you to explore whether the mean IMDB rating for Steven Spielberg and Tim Burton are the same or not. I have already calculated the confidence intervals for the mean ratings of these two directors and as you can see they overlap.</p>
<p><img src="/Users/gianmariabartoccioni/Desktop/my_website/images/directors.png" width="100%" style="display: block; margin: auto;" /></p>
<p>First, I would like you to reproduce this graph. You may find <code>geom_errorbar()</code> and <code>geom_rect()</code> useful.</p>
<p>In addition, you will run a hpothesis test. You should use both the <code>t.test</code> command and the <code>infer</code> package to simulate from a null distribution, where you assume zero difference between the two.</p>
<blockquote>
<p>Before anything, write down the null and alternative hypotheses, as well as the resulting test statistic and the associated t-stat or p-value. At the end of the day, what do you conclude?</p>
</blockquote>
<p>–&gt; OUR ANSWER BELOW &lt;—</p>
<p>Null Hypothesis- both Spielberg and Burton have the same mean rating.
Alternative Hypothesis- Spielberg and Burton have the distinct mean ratings.
p-value- /alpha=0.05</p>
<p>–&gt; END OF OUR ANSWER &lt;—</p>
<p>You can load the data and examine its structure</p>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Avenge…
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;…
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevorrow…
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015, 20…
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93, 1…
## $ gross               &lt;dbl&gt; 7.61e+08, 6.59e+08, 6.52e+08, 6.23e+08, 5.33e+08, …
## $ budget              &lt;dbl&gt; 2.37e+08, 2.00e+08, 1.50e+08, 2.20e+08, 1.85e+08, …
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, 920…
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658, 9…
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752, 35…
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7.2, …</code></pre>
<p>Recall the IMBD ratings data. I would like you to explore whether the mean IMDB rating for Steven Spielberg and Tim Burton are the same or not. I have already calculated the confidence intervals for the mean ratings of these two directors and as you can see they overlap.</p>
<p>Your R code and analysis should go here. If you want to insert a blank chunk of R code you can just hit <code>Ctrl/Cmd+Alt+I</code></p>
<pre class="r"><code>#exploring whether the mean IMDB rating for Steven Spielberg and Tim Burton are the same or not
movies_new&lt;-movies %&gt;%
  filter(director %in% c(&quot;Steven Spielberg&quot;,&quot;Tim Burton&quot;))%&gt;%
  group_by(director) 
mean_movies_director&lt;- movies_new %&gt;%
  summarise(mean_rating=mean(rating))
mean_movies_director</code></pre>
<pre><code>## # A tibble: 2 × 2
##   director         mean_rating
##   &lt;chr&gt;                  &lt;dbl&gt;
## 1 Steven Spielberg        7.57
## 2 Tim Burton              6.93</code></pre>
<pre class="r"><code>#comparing two confidence intervals for two directors-Steven Spielberg and Tim Burton
ci_rating&lt;- movies %&gt;%
  filter(director %in% c(&quot;Steven Spielberg&quot;,&quot;Tim Burton&quot;))%&gt;%
  group_by(director) %&gt;%
  
  #compute the statistics we want to analyse
  summarize(mean_rating=mean(rating),
            median_rating=median(rating,na.rm=TRUE),
            sd_rating=sd(rating),
                  count=n(),
                  se_rating=sd_rating/sqrt(count),
            max_rating=max(rating),
            min_rating=min(rating),
            t_critical=qt(0.975,count-1),
            margin_of_error=t_critical*se_rating,
            lower_ci_95=mean_rating-t_critical*se_rating,
            higher_ci_95=mean_rating+t_critical*se_rating)
ci_rating</code></pre>
<pre><code>## # A tibble: 2 × 12
##   director         mean_rating median_rating sd_rating count se_rating max_rating
##   &lt;chr&gt;                  &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 Steven Spielberg        7.57           7.6     0.695    23     0.145        8.9
## 2 Tim Burton              6.93           7       0.749    16     0.187        8  
## # … with 5 more variables: min_rating &lt;dbl&gt;, t_critical &lt;dbl&gt;,
## #   margin_of_error &lt;dbl&gt;, lower_ci_95 &lt;dbl&gt;, higher_ci_95 &lt;dbl&gt;</code></pre>
<pre class="r"><code>#having a t test
t.test(rating~director,data=movies_new)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  rating by director
## t = 3, df = 31, p-value = 0.01
## alternative hypothesis: true difference in means between group Steven Spielberg and group Tim Burton is not equal to 0
## 95 percent confidence interval:
##  0.16 1.13
## sample estimates:
## mean in group Steven Spielberg       mean in group Tim Burton 
##                           7.57                           6.93</code></pre>
<pre class="r"><code>#using infer package
direc_rating_diff &lt;- movies_new %&gt;%
  specify(rating ~ director) %&gt;%
  calculate(stat = &quot;diff in means&quot;,order= c(&quot;Steven Spielberg&quot;, &quot;Tim Burton&quot;))

null_dist_movies &lt;- movies_new %&gt;%
  #specify variables
  specify(rating ~ director) %&gt;%
  
  #assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  #generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  #calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;,order= c(&quot;Steven Spielberg&quot;, &quot;Tim Burton&quot;))

#plot the histogram
ggplot(data = null_dist_movies, aes(x = stat)) +
  geom_histogram(bins = 30)+
  theme_bw()+
  labs(title=&quot;Null distance movies&quot;)</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/IMDB%20ratings%20analysis-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist_movies %&gt;% 
  visualize() +
  shade_p_value(obs_stat = direc_rating_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/IMDB%20ratings%20analysis-2.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#compute the p-value
null_dist_movies %&gt;%
  get_p_value(obs_stat = direc_rating_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1   0.006</code></pre>
<pre class="r"><code>#replicating the graph showing confidence interval of movie ratings directed by two directors
ggplot(ci_rating, aes(x=reorder(director, mean_rating), y=mean_rating, colour=director)) +
  geom_point(size=5) +
  geom_errorbar(width=.1, aes(ymin=lower_ci_95, ymax=higher_ci_95),size=3) + 
  geom_text(aes(x=reorder(director, mean_rating),
                y=mean_rating,
                label=round(mean_rating,2)),
            size=4,
            vjust=-1,
            colour=&quot;black&quot;)+
  geom_text(aes(x=reorder(director, mean_rating),
                y=lower_ci_95,
                label=round(lower_ci_95,2)),
            size=3,
            vjust=-1,
            colour=&quot;black&quot;)+
  geom_text(aes(x=reorder(director, mean_rating),
                y=higher_ci_95,
                label=round(higher_ci_95,2)),
            size=3,
            vjust=-1,
            colour=&quot;black&quot;)+
  geom_rect(aes(xmin=0,xmax=3,ymin = 7.27, ymax=7.33), fill = &quot;grey&quot;,colour=&quot;light grey&quot;,alpha=0.55)+
  labs(x=&quot; &quot;,
       y= &quot;Mean IMDB Rating&quot;, 
       title=&quot;Do Spielberg and Burton have the same mean IMDB ratings?&quot;,
       subtitle=&quot;95% confidence intervals overlap&quot;) + 
  theme_bw()+
  coord_flip()+
  theme(legend.position = &quot;none&quot;,
        plot.title=element_text(size=10,face =&quot;bold&quot;),
        plot.subtitle = element_text(size=9,face=&quot;bold&quot;),
        axis.text.x = element_text(size=6),
        axis.text.y= element_text(size=6),
        axis.title.x =element_text(size=8,face=&quot;bold&quot;),
        strip.text.x = element_text(size=8),
        strip.text.y=element_text(size=8),
        aspect.ratio=0.6)</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/confidence_interval%20comp-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>You are asked to carry out the analysis. The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635…
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma…
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3…</code></pre>
<pre class="r"><code>skim(omega)</code></pre>
<table>
<caption>(#tab:load_omega_data)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">omega</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">50</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">salary</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">68717</td>
<td align="right">8638.2</td>
<td align="right">47033</td>
<td align="right">63303.16</td>
<td align="right">68847</td>
<td align="right">74777.7</td>
<td align="right">84576</td>
<td align="left">▁▃▇▆▅</td>
</tr>
<tr class="even">
<td align="left">experience</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">14</td>
<td align="right">11.9</td>
<td align="right">0</td>
<td align="right">2.25</td>
<td align="right">15</td>
<td align="right">20.8</td>
<td align="right">44</td>
<td align="left">▇▃▅▂▁</td>
</tr>
</tbody>
</table>
</div>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender ?</h2>
<p>The data frame <code>omega</code> contains the salaries for the sample of 50 executives in the company. Can you conclude that there is a significant difference between the salaries of the male and female executives?</p>
<p>Note that you can perform different types of analyses, and check whether they all lead to the same conclusion</p>
<p>. Confidence intervals
. Hypothesis testing
. Correlation analysis
. Regression</p>
<p>Calculate summary statistics on salary by gender. Also, create and print a dataframe where, for each gender, you show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% condifence interval</p>
<pre class="r"><code># Summary Statistics of salary by gender
mosaic::favstats (salary ~ gender, data=omega)</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, 
# the t-critical value, the standard error, the margin of error, 
# and the low/high endpoints of a 95% condidence interval

#create a new dataframe
omega_new&lt;- omega %&gt;%
  na.omit() %&gt;%
  group_by(gender) %&gt;%
  
  #compute the statistics we want to analyse
  summarize(mean_salary=mean(salary),
         sd_salary=sd(salary),
         sample_size=n(),
         t_critical=qt(0.975,sample_size-1),
         se_salary=sd_salary/sqrt(sample_size),
         margin_of_error=t_critical*se_salary,
         lower_ci_95=mean_salary-t_critical*se_salary,
         higher_ci_95=mean_salary+t_critical*se_salary)

#print our statistics table
omega_new</code></pre>
<pre><code>## # A tibble: 2 × 9
##   gender mean_salary sd_salary sample_size t_critical se_salary margin_of_error
##   &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;       &lt;int&gt;      &lt;dbl&gt;     &lt;dbl&gt;           &lt;dbl&gt;
## 1 female      64543.     7567.          26       2.06     1484.           3056.
## 2 male        73239.     7463.          24       2.07     1523.           3151.
## # … with 2 more variables: lower_ci_95 &lt;dbl&gt;, higher_ci_95 &lt;dbl&gt;</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
</blockquote>
<p>–&gt; OUR ANSWER BELOW &lt;–</p>
<p>The salaries of the male executives are around 15% more than female supported by min,median,max, and mean numbers.Additionally, the CIs do not overlap and the t_critical also &gt;2, which can be clearly concluded that there is a different between the salary payment.</p>
<p>–&gt; END OF OUR ANSWER &lt;–</p>
<p>You can also run a hypothesis testing, assuming as a null hypothesis that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money. You should tun your hypothesis testing using <code>t.test()</code> and with the simulation method from the <code>infer</code> package.</p>
<pre class="r"><code># hypothesis testing using t.test() 
omega&lt;- omega %&gt;%
  na.omit()

#do a t-test
t.test(salary ~ gender ,data=omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<pre class="r"><code>#using infer package
gender_salary_diff &lt;- omega %&gt;%
  na.omit()%&gt;%
  specify(salary ~ gender) %&gt;%
  calculate(stat = &quot;diff in means&quot;,order= c(&quot;male&quot;, &quot;female&quot;))

null_dist_salary &lt;- omega %&gt;%
  na.omit()%&gt;%
  
  #specify variables
  specify(salary ~ gender) %&gt;%
  
  #assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  #generate 2000 reps, of type &quot;permute&quot;
  generate(reps = 2000, type = &quot;permute&quot;) %&gt;%
  
  # alculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;,order=  c(&quot;male&quot;, &quot;female&quot;))

#plot the histogram
ggplot(data = null_dist_salary, aes(x = stat)) +
  geom_histogram(bins = 30)+
  labs(title=&quot;Null salary distribution&quot;)+
  theme(plot.title=element_text(size=15,face=&quot;bold&quot;,hjust=0.5))</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/hypothesis_testing-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#compute the p-value
null_dist_salary %&gt;% 
  visualize() +
  shade_p_value(obs_stat = gender_salary_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/hypothesis_testing-2.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist_salary %&gt;%
  get_p_value(obs_stat = gender_salary_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
</blockquote>
<p>P-values calculated from hypothesis testing and t.test() are totally the same.
From hypothesis testing’s outcome, we can reject the null hypothesis and draw a conclusion that there is a statistically significant difference in average salaries between male and female, as indicated by a fully negative confidence interval.
The conclusion is supported by a small p-value of 0.0002 and t = -4, larger than critical value of 2.01 for 48 degrees of freedom.</p>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience. A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of salary by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<pre class="r"><code>t.test (experience ~ gender, data=omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<pre class="r"><code>cor(omega$salary,omega$experience)</code></pre>
<pre><code>## [1] 0.803</code></pre>
<p>Based on this evidence, can you conclude that there is a significant difference between the experience of the male and female executives? Perform similar analyses as in the previous section. Does your conclusion validate or endanger your conclusion about the difference in male and female salaries?</p>
<p>–&gt; OUR ANSWER BELOW &lt;–</p>
<p>We can conclude that there is a significant difference between the experience of the male and female executives. In also completing a t-test, we can see that this difference is statistically significant. This discovery endangers our conclusions about salary since we can see a high correlation between experience and salary, implying the two variables are not independent, and thus our conclusion about gender bias is skewed since we haven’t normalised with respect to experience.</p>
<p>–&gt; END OF OUR ANSWER &lt;—</p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<p>Analyse the relationship between salary and experience. Draw a scatterplot to visually inspect the data</p>
<pre class="r"><code>#plot the graph
ggplot(omega, aes(x=experience, y = salary,colour = gender))+
  geom_point()+ 
  
  #rescale our axes for increased readability
  scale_x_continuous()+
  scale_y_log10()+
  theme_bw() +
  labs (
    title = &quot;Salary by experience of male and female &quot;,
    subtitle= &quot;scatterplot showing the samples&quot;,
    x=&quot;year of experience&quot;,
    y=&quot;salary&quot;)+
  theme(plot.title=element_text(size=15,face=&quot;bold&quot;),
        axis.title=element_text(size=12, face=&quot;bold&quot;))+
  NULL</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/salary_exp_scatter-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>You can use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make ths plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  #order the variables that will appear in ggpairs()
  select(gender, experience, salary) %&gt;% 
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Look at the salary vs experience scatterplot. What can you infer from this plot? Explain in a couple of sentences</p>
</blockquote>
<p>According to the plots,they show that with the same experiences i.e. between 15-30 years, the salary paid to male is more than women.The salary gap is around 15% according to the median.
Female also have higher correlation of 0.812 between salary and experience more than male of 0.661 showing that women tend to pay according to the year of experience while for male,the salary paid and experience are less related.</p>
</div>
</div>
<div id="challenge-1-yield-curve-inversion" class="section level1">
<h1>Challenge 1: Yield Curve inversion</h1>
<p>Every so often, we hear warnings from commentators on the “inverted yield curve” and its predictive power with respect to recessions. An explainer what a <a href="https://www.reuters.com/article/us-usa-economy-yieldcurve-explainer/explainer-what-is-an-inverted-yield-curve-idUSKBN1O50GA">inverted yield curve is can be found here</a>. If you’d rather listen to something, here is a great podcast from <a href="https://www.podbean.com/media/share/dir-4zgj9-6aefd11">NPR on yield curve indicators</a></p>
<p>In addition, many articles and commentators think that, e.g., <a href="https://www.bloomberg.com/news/articles/2019-08-14/u-k-yield-curve-inverts-for-first-time-since-financial-crisis"><em>Yield curve inversion is viewed as a harbinger of recession</em></a>. One can always doubt whether inversions are truly a harbinger of recessions, and <a href="https://twitter.com/5_min_macro/status/1161627360946511873">use the attached parable on yield curve inversions</a>.</p>
<p><img src="/Users/gianmariabartoccioni/Desktop/my_website/images/yield_curve_parable.jpg" width="100%" style="display: block; margin: auto;" /></p>
<p>In our case we will look at US data and use the <a href="https://fred.stlouisfed.org/">FRED database</a> to download historical yield curve rates, and plot the yield curves since 1999 to see when the yield curves flatten. If you want to know more, a very nice article that explains the <a href="https://fredblog.stlouisfed.org/2018/10/the-data-behind-the-fear-of-yield-curve-inversions/">yield curve is and its inversion can be found here</a>. At the end of this challenge you should produce this chart</p>
<p><img src="/Users/gianmariabartoccioni/Desktop/my_website/images/yield_curve_challenge.png" width="100%" style="display: block; margin: auto;" /></p>
<p>First, we will load the yield curve data file that contains data on the yield curve since 1960-01-01</p>
<pre class="r"><code>yield_curve &lt;- read_csv(here::here(&quot;data&quot;, &quot;yield_curve.csv&quot;))

glimpse(yield_curve)</code></pre>
<pre><code>## Rows: 6,884
## Columns: 5
## $ date      &lt;date&gt; 1960-01-01, 1960-02-01, 1960-03-01, 1960-04-01, 1960-05-01,…
## $ series_id &lt;chr&gt; &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS…
## $ value     &lt;dbl&gt; 4.35, 3.96, 3.31, 3.23, 3.29, 2.46, 2.30, 2.30, 2.48, 2.30, …
## $ maturity  &lt;chr&gt; &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, …
## $ duration  &lt;chr&gt; &quot;3-Month Treasury Bill&quot;, &quot;3-Month Treasury Bill&quot;, &quot;3-Month T…</code></pre>
<p>Our dataframe <code>yield_curve</code> has five columns (variables):</p>
<ul>
<li><code>date</code>: already a date object</li>
<li><code>series_id</code>: the FRED database ticker symbol</li>
<li><code>value</code>: the actual yield on that date</li>
<li><code>maturity</code>: a short hand for the maturity of the bond</li>
<li><code>duration</code>: the duration, written out in all its glory!</li>
</ul>
<div id="plotting-the-yield-curve" class="section level2">
<h2>Plotting the yield curve</h2>
<p>This may seem long but it should be easy to produce the following three plots</p>
<div id="yields-on-us-rates-by-duration-since-1960" class="section level3">
<h3>Yields on US rates by duration since 1960</h3>
<p><img src="/Users/gianmariabartoccioni/Desktop/my_website/images/yield_curve1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>—&gt; YIELD GRAPH #1 REPRODUCTION BELOW &lt;—
<img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/yield_curve_1_exercise-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="monthly-yields-on-us-rates-by-duration-since-1999-on-a-year-by-year-basis" class="section level3">
<h3>Monthly yields on US rates by duration since 1999 on a year-by-year basis</h3>
<p><img src="/Users/gianmariabartoccioni/Desktop/my_website/images/yield_curve2.png" width="100%" style="display: block; margin: auto;" />
—&gt; YIELD GRAPH #2 REPRODUCTION BELOW &lt;—</p>
<pre class="r"><code>#create a vector to order the maturities
order_2 &lt;- c(&quot;3m&quot;,&quot;6m&quot;,&quot;1y&quot;,&quot;2y&quot;,&quot;3y&quot;,&quot;5y&quot;,&quot;7y&quot;,&quot;10y&quot;,&quot;20y&quot;,&quot;30y&quot;)

yield_curve_2 &lt;- yield_curve %&gt;%
  
  #selecting all the column except duration
  select(-c(series_id,duration))%&gt;%
  
  #create new columns for date, year and month
  mutate(date=ymd(date),
         year=year(date),
         month=month(date)) %&gt;%
  
  #filter for the year after 1999
  filter(year&gt;=1999)

yield_curve_2 %&gt;%
  
  #create a new column with the maturities order as set above with the vector we created
  mutate(maturity=fct_relevel(maturity,order_2))%&gt;%
  
  #plot the graph
ggplot(aes(x=maturity, y=value, color=year))+
  
  #create a line graph, group by month and remove the legend 
  geom_line(aes(group=month),show.legend = FALSE)+
  
  #color the year with rainbow colours
  scale_color_gradientn(colors = rainbow(23))+
  
  #facet by year and set the column number to 4
  facet_wrap(~year,ncol=4)+
  
  #set the proper theme, titles and caption
  theme_bw()+
  labs(title=&quot;US Yield Curve&quot;,
       y=&quot;Maturity&quot;,
       x=&quot;Yield (%)&quot;,
       caption=&quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;)</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/replicate_yield_curve_2-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="month-and-10-year-yields-since-1999" class="section level3">
<h3>3-month and 10-year yields since 1999</h3>
<p><img src="/Users/gianmariabartoccioni/Desktop/my_website/images/yield_curve3.png" width="100%" style="display: block; margin: auto;" />
—&gt; YIELD GRAPH #3 REPRODUCTION BELOW &lt;—</p>
<pre class="r"><code>yield_curve_2bis &lt;- yield_curve %&gt;%
  
  #create column for the date, year and month
  mutate(date=ymd(date),
         year=year(date),
         month=month(date)) %&gt;%
  
  #filter for the year after 1999 and the maturities we are interested in
  filter(year&gt;=1999,
         duration%in% c(&quot;3-Month Treasury Bill&quot;,&quot;10-Year Treasury Rate&quot;))

yield_curve_2bis %&gt;%
  
#plot the graph
ggplot(aes(x=date, y=value, colour=duration))+
  
  #create a line graph
  geom_line()+
  
  #set the proper theme, titles and caption
  theme_bw()+
  labs(title=&quot;Yields on 3-month and 10-year US Treasury rates since 1999&quot;,
       y=&quot;%&quot;,
       x=&quot;&quot;,
       caption=&quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;)+
  
  #remove the legend title
  scale_color_discrete(name=&quot;&quot;)</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/yield_curve_3_exercise-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>According to <a href="https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States">Wikipedia’s list of recession in the United States</a>, since 1999 there have been two recession in the US: between Mar 2001–Nov 2001 and between Dec 2007–June 2009. Does the yield curve seem to flatten before these recessions? Can a yield curve flattening really mean a recession is coming in the US? Since 1999, when did short-term (3 months) yield more than longer term (10 years) debt?</p>
<p>–&gt; OUR ANSWER BELOW &lt;–</p>
<p>The yield curve seems to flatten before the recession, and this can indicate a recession as can be clearly seen on the graphs during 1999 – 2000 and 2005 - 2006. There is a smaller yield differential between short and long-term debt, an anticipation of tighter monetary policy and economic uncertainty. Short-term yield was more than long term debt during August 2000 – December 2000 and August 2006 to April 2007.</p>
<p>–&gt; END OF OUR ANSWER &lt;–</p>
<p>Besides calculating the spread (10year - 3months), there are a few things we need to do to produce our final plot</p>
<ol style="list-style-type: decimal">
<li>Setup data for US recessions</li>
<li>Superimpose recessions as the grey areas in our plot</li>
<li>Plot the spread between 30 years and 3 months as a blue/red ribbon, based on whether the spread is positive (blue) or negative(red)</li>
</ol>
<ul>
<li>For the first, the code below creates a dataframe with all US recessions since 1946</li>
</ul>
<pre class="r"><code># get US recession dates after 1946 from Wikipedia 
# https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States

recessions &lt;- tibble(
  from = c(&quot;1948-11-01&quot;, &quot;1953-07-01&quot;, &quot;1957-08-01&quot;, &quot;1960-04-01&quot;, &quot;1969-12-01&quot;, &quot;1973-11-01&quot;, &quot;1980-01-01&quot;,&quot;1981-07-01&quot;, &quot;1990-07-01&quot;, &quot;2001-03-01&quot;, &quot;2007-12-01&quot;,&quot;2020-02-01&quot;),  
  to = c(&quot;1949-10-01&quot;, &quot;1954-05-01&quot;, &quot;1958-04-01&quot;, &quot;1961-02-01&quot;, &quot;1970-11-01&quot;, &quot;1975-03-01&quot;, &quot;1980-07-01&quot;, &quot;1982-11-01&quot;, &quot;1991-03-01&quot;, &quot;2001-11-01&quot;, &quot;2009-06-01&quot;, &quot;2020-04-30&quot;) 
  )  %&gt;% 
  mutate(From = ymd(from), 
         To=ymd(to),
         duration_days = To-From)

recessions</code></pre>
<pre><code>## # A tibble: 12 × 5
##    from       to         From       To         duration_days
##    &lt;chr&gt;      &lt;chr&gt;      &lt;date&gt;     &lt;date&gt;     &lt;drtn&gt;       
##  1 1948-11-01 1949-10-01 1948-11-01 1949-10-01 334 days     
##  2 1953-07-01 1954-05-01 1953-07-01 1954-05-01 304 days     
##  3 1957-08-01 1958-04-01 1957-08-01 1958-04-01 243 days     
##  4 1960-04-01 1961-02-01 1960-04-01 1961-02-01 306 days     
##  5 1969-12-01 1970-11-01 1969-12-01 1970-11-01 335 days     
##  6 1973-11-01 1975-03-01 1973-11-01 1975-03-01 485 days     
##  7 1980-01-01 1980-07-01 1980-01-01 1980-07-01 182 days     
##  8 1981-07-01 1982-11-01 1981-07-01 1982-11-01 488 days     
##  9 1990-07-01 1991-03-01 1990-07-01 1991-03-01 243 days     
## 10 2001-03-01 2001-11-01 2001-03-01 2001-11-01 245 days     
## 11 2007-12-01 2009-06-01 2007-12-01 2009-06-01 548 days     
## 12 2020-02-01 2020-04-30 2020-02-01 2020-04-30  89 days</code></pre>
<pre class="r"><code>yield_curve_4 &lt;- yield_curve %&gt;%
  
  #select all the column except the duration variable
  select(-c(series_id,duration))%&gt;% 
  
  #create a year column
  mutate(date=ymd(date), 
         year=year(date))%&gt;%
  
  #filter for the maturities we will use to compute the yield difference
  filter(maturity %in% c(&quot;3m&quot;,&quot;10y&quot;)) 

yield_curve_5 &lt;- yield_curve_4 %&gt;%
  
  #make our data set wide with the two maturities we need to compute the difference
  pivot_wider(names_from = maturity, 
              values_from = value) %&gt;%
  
  #create a new column to obtain the difference bewteen the two maturities
  mutate(diff = `10y` - `3m`) %&gt;%
  
  #create new columns to color the areas below and above the x=0 axis in respectively red and blue
  mutate(positive=if_else(0&lt;diff,diff,0), 
         negative=if_else(0&gt;diff,diff,0),
         #setting the right color ID
         colorID=if_else(0&lt;diff,&quot;#F4B2B6&quot;,&quot;#A4C7E9&quot;)) 

yield_curve_5 %&gt;% 
  
#plot the graph
ggplot(aes(x=date, y=diff))+ 
  
  #create a line graph
  geom_line(show.legend = FALSE)+ 
  
  #grey the background areas during which the recessions occurred
  geom_rect(aes(xmin = as.Date(&quot;1960-04-01&quot;),xmax = as.Date(&quot;1961-02-01&quot;),ymin=-Inf,ymax=Inf), alpha=0.01, fill=&quot;gray&quot;)+
  geom_rect(aes(xmin = as.Date(&quot;1969-12-01&quot;),xmax = as.Date(&quot;1970-11-01&quot;),ymin=-Inf,ymax=Inf), alpha=0.01, fill=&quot;gray&quot;)+
  geom_rect(aes(xmin = as.Date(&quot;1973-11-01&quot;),xmax = as.Date(&quot;1975-03-01&quot;),ymin=-Inf,ymax=Inf), alpha=0.01, fill=&quot;gray&quot;)+
  geom_rect(aes(xmin = as.Date(&quot;1980-01-01&quot;),xmax = as.Date(&quot;1980-07-01&quot;),ymin=-Inf,ymax=Inf), alpha=0.01, fill=&quot;gray&quot;)+
  geom_rect(aes(xmin = as.Date(&quot;1981-07-01&quot;),xmax = as.Date(&quot;1982-11-01&quot;),ymin=-Inf,ymax=Inf), alpha=0.01, fill=&quot;gray&quot;)+
  geom_rect(aes(xmin = as.Date(&quot;1990-07-01&quot;),xmax = as.Date(&quot;1991-03-01&quot;),ymin=-Inf,ymax=Inf), alpha=0.01, fill=&quot;gray&quot;)+
  geom_rect(aes(xmin = as.Date(&quot;2001-03-01&quot;),xmax = as.Date(&quot;2001-11-01&quot;),ymin=-Inf,ymax=Inf), alpha=0.01, fill=&quot;gray&quot;)+
  geom_rect(aes(xmin = as.Date(&quot;2007-12-01&quot;),xmax = as.Date(&quot;2009-06-01&quot;),ymin=-Inf,ymax=Inf), alpha=0.01, fill=&quot;gray&quot;)+
  geom_rect(aes(xmin = as.Date(&quot;2020-02-01&quot;),xmax = as.Date(&quot;2020-04-30&quot;),ymin=-Inf,ymax=Inf), alpha=0.01, fill=&quot;gray&quot;)+

  #color the rug whether the line is positive (blue) or negative (red)
  geom_rug(data = yield_curve_5, 
           aes(color=colorID, alpha=0.4), 
           sides = &quot;b&quot;) +
  scale_color_manual(values=c(&quot;#F4B2B6&quot;,&quot;#A4C7E9&quot;))+
  
  #color the line area in red below zero
  geom_ribbon(aes(ymin=0, ymax=negative), 
              fill=&quot;#F4B2B6&quot;, 
              alpha= 0.4)+
  geom_ribbon(aes(ymin=positive, ymax=0), 
              fill=&quot;#A4C7E9&quot;, 
              alpha= 0.4)+

  #set the proper titles and caption
  theme_bw()+
    labs(title=&quot;Yield Curve Inversion: 10-year minus 3-month US Treasury rates&quot;,
    subtitle = &quot;Difference in % points, monthly averages.\nShaded areas correspond to recessions.&quot;,
    y=&quot;Difference (10 year - 3 month) yield in %&quot;,
    x=&quot;&quot;,
    caption=&quot;Source: FRED, Federal Reserve Bank of St. Louis&quot;)+
  
  #remove the legend
  theme(legend.position = &quot;none&quot;,
        legend.background=element_blank())</code></pre>
<p><img src="/blogs/homework_3_group_B9_FINAL_files/figure-html/yield_curve_4_exercise-1.png" width="100%" style="display: block; margin: auto;" /></p>
<ul>
<li>To add the grey shaded areas corresponding to recessions, we use <code>geom_rect()</code></li>
<li>to colour the ribbons blue/red we must see whether the spread is positive or negative and then use <code>geom_ribbon()</code>. You should be familiar with this from last week’s homework on the excess weekly/monthly rentals of Santander Bikes in London.</li>
</ul>
<!-- # Challenge 2: GDP components over time and among countries -->
<!-- At the risk of oversimplifying things, the main components of gross domestic product, GDP are personal consumption (C), business investment (I), government spending (G) and net exports (exports - imports). You can read more about GDP and the different approaches in calculating at the [Wikipedia GDP page](https://en.wikipedia.org/wiki/Gross_domestic_product). -->
<!-- The GDP data we will look at is from the [United Nations' National Accounts Main Aggregates Database](https://unstats.un.org/unsd/snaama/Downloads), which contains estimates of total GDP and its components for all countries from 1970 to today. We will look at how GDP and its components have changed over time, and compare different countries and how much each component contributes to that country's GDP. The file we will work with is [GDP and its breakdown at constant 2010 prices in US Dollars](http://unstats.un.org/unsd/amaapi/api/file/6) and it has already been saved in the Data directory. Have a look at the Excel file to see how it is structured and organised -->
<!-- ```{r read_GDP_data, cache=TRUE} -->
<!-- UN_GDP_data  <- read_excel(here::here("data", "Download-GDPconstant-USD-countries.xls"), # Excel filename -->
<!--                 sheet="Download-GDPconstant-USD-countr", # Sheet name -->
<!--                 skip=2) # Number of rows to skip -->
<!-- ``` -->
<!-- The first thing you need to do is to tidy the data, as it is in wide format and you must make it into long, tidy format. Please express all figures in billions (divide values by `1e9`, or $10^9$), and you want to rename the indicators into something shorter. -->
<!-- ```{r reshape_GDP_data, cache=TRUE} -->
<!-- #convert the data to long format -->
<!-- tidy_GDP_data  <-  pivot_longer(UN_GDP_data, cols = 4:51, #using the the columns 4 to 51 to make a long table -->
<!--                                 names_to = "Years", -->
<!--                                 values_to = "Values")  -->
<!-- #clean the data - values to billions, set the variables properly and rename indicators -->
<!-- tidy_GDP_data<- tidy_GDP_data %>%  -->
<!--   mutate(Values=Values/10^9) %>% -->
<!--   mutate(across(Years,as.numeric)) %>% #set "Years" as a numeric variable -->
<!--   mutate(across(Country,as.character)) %>% -->
<!--   rename(Indicator=IndicatorName)  -->
<!-- #check which indicators and countries to change -->
<!-- tidy_GDP_data %>% distinct(Indicator) -->
<!-- tidy_GDP_data %>% distinct(Country) -->
<!-- #we get an error message when recoding in pipe, so we use base R based on suggestions from StackOverFlow  -->
<!-- #the error we get is <<Error in UseMethod("recode") : no applicable method for 'recode' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')">> -->
<!-- #rename the indicators using the recode function -->
<!-- tidy_GDP_data$Indicator <- recode(tidy_GDP_data$Indicator,  -->
<!--                                   "Agriculture, hunting, forestry, fishing (ISIC A-B)"="Agriculture", -->
<!--                                   "Changes in inventories"="Inventory changes", -->
<!--                                   "Construction (ISIC F)"="Construction", -->
<!--                                   "Exports of goods and services"="Exports", -->
<!--                                   "Final consumption expenditure"="Final consumption", -->
<!--                                   "General government final consumption expenditure"="Government expenditure", -->
<!--                                  # "Gross Domestic Product (GDP)"="GPD", -->
<!--                                   "Gross fixed capital formation (including Acquisitions less disposals of valuables)"="Fixed capital formation", -->
<!--                                   "Household consumption expenditure (including Non-profit institutions serving households)"="Household expenditure", -->
<!--                                   "Imports of goods and services"="Imports", -->
<!--                                   "Manufacturing (ISIC D)"="Manufacturing", -->
<!--                                   "Other Activities (ISIC J-P)"="Other", -->
<!--                                   "Total Value Added"="Value added", -->
<!--                                   "Transport, storage and communication (ISIC I)"="Transport", -->
<!--                                   "Wholesale, retail trade, restaurants and hotels (ISIC G-H)"="Wholesale") -->
<!-- tidy_GDP_data <- tidy_GDP_data %>%  -->
<!--   select("Country", "Indicator", "Years", "Values") -->
<!-- # Let us compare GDP components for these 3 countries -->
<!-- country_list <- c("United States","India", "Germany") -->
<!-- #creat a data frame filtered with the vector containing the three countries we want to compare -->
<!-- tidy_GDP_data_3 <- tidy_GDP_data %>% -->
<!--   filter(Country %in% country_list) -->
<!-- ``` -->
<!-- First, can you produce this plot? -->
<!-- ```{r gdp1, echo=FALSE, out.width="100%", cache=TRUE} -->
<!-- knitr::include_graphics(here::here("images", "gdp1.png"), error = FALSE) -->
<!-- ``` -->
<!-- ```{r gdp1_plot, cache=TRUE, out.width="100%"} -->
<!-- #create the vector of the indicators we want  -->
<!-- indicator_list_1 <- c("Gross capital formation", "Exports", "Government expenditure", "Household expenditure", "Imports") -->
<!-- #selecting our tidy data frame that has been filtered for the Germany, India and the US -->
<!-- tidy_GDP_data_3 %>% -->
<!--   #filter the indicators with the vector we created -->
<!--   filter(Indicator %in% indicator_list_1) %>% -->
<!--   #plot the graph with the right aesthetics -->
<!--   ggplot(aes(x = Years, y = Values, colour = Indicator))+ -->
<!--   #group by indicator -->
<!--   geom_line(aes(group=Indicator))+ -->
<!--   #facet by country and set the column number to 3 -->
<!--   facet_wrap(~Country,ncol=3)+ -->
<!--   #set the proper theme, titles and caption -->
<!--   theme_bw()+ -->
<!--   labs(title="GDP components over time", -->
<!--        subtitle = "In constant 2010 USD", -->
<!--        color = "Components of  GDP", -->
<!--        y="Billion US$", -->
<!--        x="") -->
<!-- ``` -->
<!-- Secondly, recall that GDP is the sum of Household Expenditure (Consumption *C*), Gross Capital Formation (business investment *I*), Government Expenditure (G) and Net Exports (exports - imports). Even though there is an indicator `Gross Domestic Product (GDP)` in your dataframe, I would like you to calculate it given its components discussed above. -->
<!-- > What is the % difference between what you calculated as GDP and the GDP figure included in the dataframe? -->
<!-- -->
<p>OUR ANSWER BELOW &lt;– –&gt;</p>
<!-- ```{r GDP differences, cache=TRUE} -->
<!-- library(tidyverse) -->
<!-- #creating vector of the countries we want to analyse -->
<!-- country_list_3 <- c("Germany","India","United States") -->
<!-- #create a vector of the of indicators which we will then widen in our pivot_wider -->
<!-- indicator_list_2 <- c("Gross capital formation", "Exports", "Government expenditure", "Household expenditure", "Imports","Gross Domestic Product (GDP)") -->
<!-- #create a new dataframe -->
<!-- tidy_GDP_data_6 <- tidy_GDP_data %>% -->
<!--   #filter for the indicators and countries that are of interest to us -->
<!--   filter(Country %in% country_list_3) %>% -->
<!--   filter(Indicator %in% indicator_list_2) %>% -->
<!--   #pivot wider with the indicators we filtered to then compute the Net Exports and the proportion of GDP component -->
<!--   pivot_wider(names_from = Indicator, -->
<!--               values_from = Values) %>% -->
<!--   #create new columns to compute the Net Exports so as to be able to compare the GDP with the four components (G + I + C + (X-M)) to the GDP indicator already embedded in the original UN file -->
<!--   mutate("Net Exports" = `Exports` - `Imports`, -->
<!--          "Total GDP" = `Net Exports` + `Gross capital formation` + `Government expenditure` + `Household expenditure`, -->
<!--          "GDP Difference"= `Total GDP`-`Gross Domestic Product (GDP)`, -->
<!--          "GDP Percentage Change"= 100*`GDP Difference`/`Total GDP`)%>% -->
<!--   #make the table long again to stack the indicators together -->
<!--   pivot_longer(cols = 3:12, #using the the columns 2 to 13 to make a long table -->
<!--                names_to = "Indicator", -->
<!--                values_to = "Values")%>% -->
<!--   #filter for the indicators of interest to us -->
<!--   filter(Indicator %in% c("Total GDP","Gross Domestic Product (GDP)", "GDP Difference", "GDP Percentage Change")) %>%  -->
<!--   pivot_wider(names_from = Years, -->
<!--               values_from = Values) -->
<!-- tidy_GDP_data_7 <-  tidy_GDP_data_6 %>%  -->
<!--   filter(Indicator == "GDP Percentage Change") %>%  -->
<!--   #pivot longer to compare the differences of GDP for the three countries we are interest in -->
<!--   pivot_longer(cols = 3:50, #using the the columns 2 to 51 to make a long table -->
<!--                names_to = "Years", -->
<!--                values_to = "Values")%>% -->
<!--   pivot_wider(names_from = Country, -->
<!--               values_from = Values) -->
<!--   #compute statistics regarding the GDP difference for Germany -->
<!--   diff_germany<- tidy_GDP_data_7 %>%  -->
<!--   summarise(sample_size=n(), -->
<!--             t_critical=qt(0.975,sample_size-1), -->
<!--             mean_change_germany=mean(Germany), -->
<!--             sd_change_germany=sd(Germany), -->
<!--             se_change_germany=sd_change_germany/sqrt(sample_size), -->
<!--             lower_ci_95=mean_change_germany-t_critical*se_change_germany, -->
<!--             higher_ci_95=mean_change_germany+t_critical*se_change_germany) -->
<!--   #compute statistics regarding the GDP difference for India -->
<!--   diff_india<- tidy_GDP_data_7 %>%  -->
<!--   summarise(sample_size=n(), -->
<!--             t_critical=qt(0.975,sample_size-1), -->
<!--             mean_change_india=mean(India), -->
<!--             sd_change_india=sd(India), -->
<!--             se_change_india=sd_change_india/sqrt(sample_size), -->
<!--             lower_ci_95=mean_change_india-t_critical*se_change_india, -->
<!--             higher_ci_95=mean_change_india+t_critical*se_change_india) -->
<!--   #compute statistics regarding the GDP difference for the US -->
<!--   diff_US<- tidy_GDP_data_7 %>%  -->
<!--     summarise(sample_size=n(), -->
<!--             t_critical=qt(0.975,sample_size-1), -->
<!--             mean_change_US=mean(`United States`), -->
<!--             sd_change_US=sd(`United States`), -->
<!--             se_change_US=sd_change_US/sqrt(sample_size), -->
<!--             lower_ci_95=mean_change_US-t_critical*se_change_US, -->
<!--             higher_ci_95=mean_change_US+t_critical*se_change_US) -->
<!-- #print the differences -->
<!-- diff_germany -->
<!-- diff_india -->
<!-- diff_US -->
<!-- ``` -->
<!-- From the above, we can see an average difference of 1.11% for Germany, 0.08% for India, and 1.24% for the US, which implies that either the governments typically released underestimates, or we are lacking additional data that would cause such consistent errors. -->
<!-- -->
<p>END OF OUR ANSWER &lt;– –&gt;</p>
<!-- ```{r gdp2, echo=FALSE, out.width="100%", cache=TRUE} -->
<!-- knitr::include_graphics(here::here("images", "gdp2.png"), error = FALSE) -->
<!-- ``` -->
<!-- ```{r gdp2_plot_2, out.width="100%", cache=TRUE} -->
<!-- #create a vector of the of indicators which we will then widen in our pivot_wider -->
<!-- indicator_list_2 <- c("Gross capital formation", "Exports", "Government expenditure", "Household expenditure", "Imports") -->
<!-- #create a vector of the proportion of each GDP component which we will then lengthen in our pivot_longer.  -->
<!-- #Note: we add a space after each GDP component weight' name to differentiate them of the indicators that already exist while having them display the same way. -->
<!-- indicator_list_3 <- c("Gross capital formation ", "Net Exports ", "Government expenditure ", "Household expenditure ") -->
<!-- #create a new dataframe for the dataframe already filtered with Germany, India and the US -->
<!-- tidy_GDP_data_4 <- tidy_GDP_data_3 %>% -->
<!--   #filter for the indicators that are of interest to us -->
<!--   filter(Indicator %in% indicator_list_2) %>% -->
<!--   #pivot wider with the indicators we filtered to then compute the Net Exports and the proportion of GDP component -->
<!--   pivot_wider(names_from = Indicator, -->
<!--               values_from = Values) %>% -->
<!--   #compute the Net Exports, the total GDP and the weights of each GDP component in the total GDP. -->
<!--   mutate("Net Exports" = `Exports` - `Imports`, -->
<!--          "Total GDP" = `Net Exports` + `Gross capital formation` + `Government expenditure` + `Household expenditure`, -->
<!--          "Gross capital formation " = `Gross capital formation`/`Total GDP`, -->
<!--          "Government expenditure " = `Government expenditure`/`Total GDP`, -->
<!--          "Net Exports " = `Net Exports`/`Total GDP`, -->
<!--          "Household expenditure " = `Household expenditure`/`Total GDP`)%>% -->
<!--   #make the table long again to be able to plot the weights of each GDP component -->
<!--   pivot_longer(cols = 4:13, #using the the columns 2 to 13 to make a long table -->
<!--                names_to = "Indicator", -->
<!--                values_to = "Values")%>% -->
<!--   filter(Indicator %in% indicator_list_3) -->
<!-- #load the dataframe that contains the new variable Net Exports and the weights of the 4 variables  -->
<!-- tidy_GDP_data_4 %>% -->
<!-- ggplot(aes(x = Years, y = Values, colour = Indicator))+ -->
<!--   #create a line graph, group by month and remove the legend  -->
<!--   geom_line(aes(group=Indicator))+ -->
<!--   #facet by country -->
<!--   facet_wrap(~Country,ncol=3)+ -->
<!--   #change our y-axis for percentage -->
<!--   scale_y_continuous(labels = scales::percent)+ -->
<!--   #set the proper theme and titles -->
<!--   theme_bw()+ -->
<!--   labs(title="GDP and its breakdown at constant 2010 prices in US Dollars", -->
<!--        color = "", -->
<!--        y="proportion", -->
<!--        x="", -->
<!--        caption="Source: United Nations, https://unstats.un.org/unsd/naama/Downloads")+ -->
<!--   #remove the legend's title -->
<!--   scale_color_discrete(name="") -->
<!-- ``` -->
<!-- cache  -->
<!-- -->
<p>OUR ANSWER BELOW &lt;– –&gt;</p>
<!-- Regarding Germany, household expenditure contributes the most to the Country’s GDP during 1970 to 2016 followed by exports and imports. The government expenditure and gross capital formation reported the same trends with a very small growth during the period. Concerning India, household expenditure also accounts the most of its GDP and showed an increasing trend since 1970.  Other contributors reported flat trends during 1970 to 2000 and started to grow after that. The U.S.’s GDP reported a substantially growth comparing to the other two countries especially on household expenditures that increased almost five times during the periods. -->
<!-- -->
<p>END OF OUR ANSWER &lt;– –&gt;</p>
<!-- > If you want to, please change `country_list <- c("United States","India", "Germany")` to include your own country and compare it with any two other countries you like -->
<!-- -->
<p>OUR ANSWER BELOW &lt;— –&gt;</p>
<!-- We plotted below a chart to analyse the breakdown of each of our countries' GDP (China, Norway, United Kingdom, Thailand, Italy and France). -->
<!-- -->
<p>END OF OUR ANSWER &lt;— –&gt;</p>
<!-- ```{r gdp_plot_3, cache=TRUE} -->
<!-- #creating vector of the new countries we want to analyse -->
<!-- country_list_2 <- c("China", "Norway", "United Kingdom", "Thailand", "Italy", "France") -->
<!-- #create a vector of the of indicators which we will then widen in our pivot_wider -->
<!-- indicator_list_2 <- c("Gross capital formation", "Exports", "Government expenditure", "Household expenditure", "Imports") -->
<!-- #create a vector of the proportion of each GDP component which we will then lengthen in our pivot_longer.  -->
<!-- #Note: we add a space after each GDP component weight' name to differentiate them of the indicators that already exist while having them display the same way. -->
<!-- indicator_list_3 <- c("Gross capital formation ", "Net Exports ", "Government expenditure ", "Household expenditure ") -->
<!-- #create a new dataframe for the dataframe already filtered with Germany, India and the US -->
<!-- tidy_GDP_data_5 <- tidy_GDP_data %>% -->
<!--   #filter for the indicators that are of interest to us -->
<!--   filter(Country %in% country_list_2) %>% -->
<!--   filter(Indicator %in% indicator_list_2) %>% -->
<!--   #pivot wider with the indicators we filtered to then compute the Net Exports and the proportion of GDP component -->
<!--   pivot_wider(names_from = Indicator, -->
<!--               values_from = Values) %>% -->
<!--   #compute the Net Exports, the total GDP and the weights of each GDP component in the total GDP. -->
<!--   mutate("Net Exports" = `Exports` - `Imports`, -->
<!--          "Total GDP" = `Net Exports` + `Gross capital formation` + `Government expenditure` + `Household expenditure`, -->
<!--          "Gross capital formation " = `Gross capital formation`/`Total GDP`, -->
<!--          "Government expenditure " = `Government expenditure`/`Total GDP`, -->
<!--          "Net Exports " = `Net Exports`/`Total GDP`, -->
<!--          "Household expenditure " = `Household expenditure`/`Total GDP`)%>% -->
<!--   #make the table long again to be able to plot the weights of each GDP component -->
<!--   pivot_longer(cols = 4:13, #using the the columns 2 to 13 to make a long table -->
<!--                names_to = "Indicator", -->
<!--                values_to = "Values")%>% -->
<!--   filter(Indicator %in% indicator_list_3) -->
<!-- #load the dataframe that contains the new variable Net Exports and the weights of the 4 variables  -->
<!-- tidy_GDP_data_5 %>% -->
<!-- ggplot(aes(x = Years, y = Values, colour = Indicator))+ -->
<!--   #create a line graph, group by month and remove the legend  -->
<!--   geom_line(aes(group=Indicator))+ -->
<!--   #facet by country -->
<!--   facet_wrap(~Country,ncol=3)+ -->
<!--   #change our y-axis for percentage -->
<!--   scale_y_continuous(labels = scales::percent)+ -->
<!--   #set the proper theme and titles -->
<!--   theme_bw()+ -->
<!--   labs(title="GDP and its breakdown at constant 2010 prices in US Dollars", -->
<!--        color = "", -->
<!--        y="proportion", -->
<!--        x="", -->
<!--        caption="Source: United Nations, https://unstats.un.org/unsd/naama/Downloads")+ -->
<!--   #remove the legend's title -->
<!--   scale_color_discrete(name="") -->
<!-- ``` -->
<!-- # Deliverables -->
<!-- There is a lot of explanatory text, comments, etc. You do not need these, so delete them and produce a stand-alone document that you could share with someone. Knit the edited and completed R Markdown file as an HTML document (use the "Knit" button at the top of the script editor window) and upload it to Canvas. -->
<!-- # Details -->
<!-- - Who did you collaborate with: Only our study group B9 (Sherington AMARAPALA, Gianmaria BARTOCCIONI, Metavee LUANGTHAWORNKUL, Keshav MAHENDRA, Hadrien PISTRE, Cissie XU). -->
<!-- - Approximately how much time did you spend on this problem set: 25 hours -->
<!-- - What, if anything, gave you the most trouble: No task took us more time that the other tasks. -->
<!-- **Please seek out help when you need it,** and remember the [15-minute rule](https://mfa2022.netlify.app/syllabus/#the-15-minute-rule){target=_blank}. You know enough R (and have enough examples of code from class and your readings) to be able to do this. If you get stuck, ask for help from others, post a question on Slack-- and remember that I am here to help too!   -->
<!-- > As a true test to yourself, do you understand the code you submitted and are you able to explain it to someone else?  -->
<!-- # Rubric -->
<!-- Check minus (1/5): Displays minimal effort. Doesn't complete all components. Code is poorly written and not documented. Uses the same type of plot for each graph, or doesn't use plots appropriate for the variables being analyzed.  -->
<!-- Check (3/5): Solid effort. Hits all the elements. No clear mistakes. Easy to follow (both the code and the output).  -->
<!-- Check plus (5/5): Finished all components of the assignment correctly and addressed both challenges. Code is well-documented (both self-documented and with additional comments as necessary). Used tidyverse, instead of base R. Graphs and tables are properly labelled. Analysis is clear and easy to follow, either because graphs are labeled clearly or you've written additional text to describe how you interpret the output. -->
</div>
</div>
</div>
